name: Lint YAML

on:
  push:
    branches: [main]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".yamllint.yaml"
      - ".github/workflows/lint-yaml.yml"

  pull_request:
    branches: [main]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".yamllint.yaml"
      - ".github/workflows/lint-yaml.yml"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3.1.1
