name: Socialize

on:
  schedule:
    - cron: "1 1 * * 0"

  workflow_dispatch:

jobs:
  star-org-repositories:
    # Want to star all repositories of organization I'm part of or that I love.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        org: [okp4, axone-protocol]
    steps:
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.12

      - name: ⭐️ Star organisation repositories
        run: |
          npx \
            --yes @octoherd/script-star-or-unstar@v2.0.2 \
            --octoherd-bypass-confirms yes \
            -T "$GH_TOKEN" \
            -R "${{matrix.org}}/*"
        env:
          GH_TOKEN: ${{ secrets.SOCIALIZE_TOKEN }}

  follow-org-members:
    # Want to follow all members (and outside collaborators) of organization I'm part of or that I love.
    runs-on: ubuntu-22.04
    needs: star-org-repositories
    steps:
      - name: 🤝 Follow organisation members
        run: |
          users=""
          for org in $ORGS
          do
            org_members=$(gh api orgs/$org/members --jq '.[].login')
            users="$users $org_members"

            sleep $SLEEP_DURATION

            org_collaborators=$(gh api orgs/$org/outside_collaborators --jq '.[].login')
            users="$users $org_collaborators"

            sleep $SLEEP_DURATION
          done
          users=$(echo "$users" | tr ' ' '\n' | sort | uniq)
          for u in $users
          do
            echo "👀 follow $u"
            gh api -X PUT user/following/$u

            sleep $SLEEP_DURATION
          done
        env:
          ORGS: "okp4 axone-protocol"
          SLEEP_DURATION: 2
          GH_TOKEN: ${{ secrets.SOCIALIZE_TOKEN }}

  follow-my-followers:
    runs-on: ubuntu-22.04
    needs: follow-org-members # wait for follow-org-members to finish (prevent rate limit)
    steps:
      - name: 🤝 Follow my followers
        run: |
          USERS=$(gh api --paginate user/followers | jq '[.[].login]| unique | .[]' -r)
          for u in $USERS
          do
            echo "👀 follow $u"
            gh api -X PUT user/following/$u

            sleep $SLEEP_DURATION
          done
        env:
          SLEEP_DURATION: 2
          GH_TOKEN: ${{ secrets.SOCIALIZE_TOKEN }}
