name: Socialize

on:
  schedule:
    - cron: "1 1 * * *"

  workflow_dispatch:

jobs:
  star-okp4-repositories:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.12

      - name: ⭐️ Star OKP4 repositories
        run: |
          npx \
            --yes @octoherd/script-star-or-unstar@v2.0.1 \
            --octoherd-bypass-confirms yes \
            -T "$GH_TOKEN" \
            -R "okp4/*"
        env:
          GH_TOKEN: ${{ secrets.SOCIALIZE_TOKEN }}

  follow-okp4-members:
    runs-on: ubuntu-22.04
    steps:
      - name: 🤝 Follow OKP4 members
        run: |
          USERS=$(gh repo list okp4 --json assignableUsers | jq '[.[].assignableUsers | .[].login]| unique | .[]' -r)
          for u in $USERS
          do
            echo follow $u
            gh api -X PUT user/following/$u
          done
        env:
          GH_TOKEN: ${{ secrets.SOCIALIZE_TOKEN }}
