name: Socialize

on:
  schedule:
    - cron: "1 1 * * 0"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  star-org-repositories:
    # Want to star all repositories of organization I'm part of or that I love.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        org: [okp4, axone-protocol]
      max-parallel: 1
    steps:
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.12

      - name: ⭐️ Star organisation repositories
        run: |
          npx \
            --yes @octoherd/script-star-or-unstar@v2.0.2 \
            --octoherd-bypass-confirms yes \
            -T "$GH_TOKEN" \
            -R "${{matrix.org}}/*"
        env:
          GH_TOKEN: ${{ secrets.SOCIALIZE_TOKEN }}

  follow-guys:
    # Want to follow some guys depending on my interests.
    runs-on: ubuntu-22.04
    needs: star-org-repositories
    strategy:
      max-parallel: 1
      matrix:
        resources:
          - user/followers
          - orgs/okp4/members
          - orgs/axone-protocol/members
          - orgs/okp4/outside_collaborators
          - orgs/axone-protocol/outside_collaborators
    steps:
      - name: 🤝 Follow some guys
        run: |
          USERS=$(gh api --paginate ${{matrix.resources}} | jq '[.[].login]| unique | .[]' -r)
          for u in $USERS
          do
            echo "👀 follow $u"
            gh api -X PUT user/following/$u

            sleep $SLEEP_DURATION
          done
        env:
          SLEEP_DURATION: 2
          GH_TOKEN: ${{ secrets.SOCIALIZE_TOKEN }}
